# Generated by Django 3.0.3 on 2020-02-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20200226_1420'),
        ('movies', '0008_auto_20200226_2011'),
    ]

    operations = [
    ]
