# Generated by Django 3.0.3 on 2020-03-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_merge_20200226_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='perent',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.Reviews', verbose_name='родитель'),
        ),
    ]
